WebBanSach/WebBanSach/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanSach.Models;
using PagedList;
using PagedList.Mvc;
namespace WebBanSach.Controllers
{
    public class BookStoreController : Controller
    {
        // GET: BookStore
        dbQLBansachDataContext data = new dbQLBansachDataContext();
        private List<SACH> Laysachmoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        //public ActionResult Index()
        //{
        //    var sachmoi = Laysachmoi(6);
        //    return View(sachmoi);
        //}
        public ActionResult Index(int? page)
        {
            int pageSize = 5;
            int pageNum = (page ?? 1);

            var sachmoi = Laysachmoi(15);
            return View(sachmoi.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);

        }
        public ActionResult NhaXuatBan()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);

        }
        public ActionResult SPTheochude(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult Details(int id)
        {
            var sach = from s in data.SACHes
                       where s.Masach == id
                       select s;
            return View(sach.Single());
        }
    }
}

WebBanSach/WebBanSach/Views/BookStore/Chude.cshtml
@model IEnumerable<WebBanSach.Models.CHUDE>
@*<p class="lead"> CHỦ ĐỀ </p>*@
<div>
    @foreach (var item in Model)
    {
            <a href="@Url.Action("SPTheochude", "BookStore", new{id= item.MaCD})">
                @item.TenChuDe
            </a>
            <br />
            <br />
    }
</div>

WebBanSach/WebBanSach/Views/BookStore/Details.cshtml
@model WebBanSach.Models.SACH
<style type="text/css">
    #Datmua a {
        clear: both;
        background-color: red;
        color: white;
        width: 120px;
        height: 35px;
        display: block;
        float: right;
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
    }

        #Datmua a:hover {
            background-color: gray;
            color: red;
        }
</style>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>THÔNG TIN CHI TIẾT SÁCH</h2>
<div>
    <div style="width:25%;float:left;border-left:dotted 1px; border-color:azure">
        <img src="~/Hinhsanpham//@Model.Hinhminhhoa "width="100%"/>
    </div>
    <div style="width:60%;float:left;padding:10px">
        <h4 style="font-weight:bold;color:red">Tên sách: @Model.Tensach </h4>
        <p style="text-align:justify"><span style="font-weight:bold">Mô tả: </span>@Model.Mota</p>
        <p style="font-weight:bold">Giá bán:  <span style="color:red; font-size:16pt ">@Model.Dongia VNĐ </span></p>
    </div>
    <div>
        <div id="Datmua">
            <a href="@Url.Action("ThemGiohang","Giohang",new {@iMasach=@Model.Masach,strURL=Request.Url.ToString()})">
                ĐẶT MUA
            </a>

        </div>

    </div>
</div>

WebBanSach/WebBanSach/Views/BookStore/Index.cshtml
@using WebBanSach.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

@{
    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@*@foreach (var sach in Model)
        {
            <div class="col-sm-4">
                <div class="product-image-wrapper">
                    <div class="single-products">
                        <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })"></a>
                        <div class="productinfo text-center">
                            <img alt="@sach.Tensach" src="~/Hinhsanpham/@sach.Hinhminhhoa" style="width:150px" alt="" />
                            <h2>@sach.Dongia</h2>
                            <p>@sach.Tensach</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        </div>
                        <div class="ratings">
                            <p class="pull-right">15 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                        <div class="product-overlay">
                            <div class="overlay-content">
                                <h2>@sach.Dongia</h2>
                                <p>@sach.Tensach</p>
                                <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                            </div>
                        </div>
                    </div>
                    <div class="choose">
                        <ul class="nav nav-pills nav-justified">
                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                            <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                        </ul>
                    </div>
                </div>

            </div>
    }*@
<h2 class="title text-center">SÁCH MỚI</h2>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">

            <div class="thumbnail" style="height:350px">
                <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })">
                    <img alt="@sach.Tensach" src="~/Hinhsanpham/@sach.Hinhminhhoa" width="150" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @sach.Tensach
                        </h4>
                        <p></p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>
    }

</div>

<div style="position:relative; bottom:initial">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;
    <div class="MenuTRang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .MenuTRang li {
            display: inline;
        }
    </style>
</div>

WebBanSach/WebBanSach/Views/BookStore/NhaXuatBan.cshtml
@model IEnumerable<WebBanSach.Models.NHAXUATBAN>
@*<p class="lead"> NHÀ XUẤT BẢN </p>*@
<div>
    @foreach (var item in Model)
    {
        <a href="@Url.Action("SPTheoNXB", "BookStore", new{id= item.MaNXB})">
            @item.TenNXB
        </a>
        <br />
    }
</div>

WebBanSach/WebBanSach/Views/BookStore/SPTheoNXB.cshtml
@model IEnumerable<WebBanSach.Models.SACH>
@{
    ViewBag.Title = "SPTheoNXB";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2 class="title text-center">SÁCH THEO NHÀ XUẤT BẢN</h2>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">

            <div class="thumbnail" style="height:350px">
                <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })">
                    <img alt="@sach.Tensach" src="~/Hinhsanpham/@sach.Hinhminhhoa" width="150" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @sach.Tensach
                        </h4>
                        <p></p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>
    }

</div>



@*@foreach (var sach in Model)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })"></a>
                    <div class="productinfo text-center">
                        <img src="~/Hinhsanpham/@sach.Hinhminhhoa" style="width:150px" alt="" />
                        <h2>@sach.Dongia</h2>
                        <p>@sach.Tensach</p>
                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>@sach.Dongia</h2>
                            <p>@sach.Tensach</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        </div>
                    </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                    </ul>
                </div>
            </div>

        </div>
    }*@

WebBanSach/WebBanSach/Views/BookStore/SPTheochude.cshtml
@model IEnumerable<WebBanSach.Models.SACH>

@{
                /**/

                ViewBag.Title = "SPTheochude";
                Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2 class="title text-center">SÁCH THEO CHỦ ĐỀ</h2>

<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">

            <div class="thumbnail" style="height:350px">
                <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })">
                    <img alt="@sach.Tensach" src="~/Hinhsanpham/@sach.Hinhminhhoa" width="150" />
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @sach.Tensach
                        </h4>
                        <p></p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                </a>
            </div>
        </div>
    }
    @*<div class="col-sm-4 col-lg-4 col-md-4">
            <H4><a href="#">Like this template</a></H4>
            <p>If you like this template, then checkout this tutorial on how to buld a working review system for your online store!<a target="_blank" href=""></a></p>
            <a class="btn btn-primary" target="_blank" href="">View Tutorial</a>
        </div>*@
</div>
@*@foreach (var sach in Model)
    {
        <div class="col-sm-4">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })"></a>
                    <div class="productinfo text-center">
                        <img src="~/Hinhsanpham/@sach.Hinhminhhoa" style="width:150px" alt="" />
                        <h2>@sach.Dongia</h2>
                        <p>@sach.Tensach</p>
                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                    <div class="ratings">
                        <p class="pull-right">15 reviews</p>
                        <p>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                            <span class="glyphicon glyphicon-star"></span>
                        </p>
                    </div>
                    <div class="product-overlay">
                        <div class="overlay-content">
                            <h2>@sach.Dongia</h2>
                            <p>@sach.Tensach</p>
                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                        </div>
                    </div>
                </div>
                <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                        <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                    </ul>
                </div>
            </div>

        </div>
    }*@